name: 'jaffle_shop'
version: '1.0.0'

profile: 'jaffle_shop'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

vars:
  seeds_schema: 'jaffle_shop_bronze'
  "dbt_date:time_zone": "America/Los_Angeles"

seeds:
  +schema: jaffle_shop_bronze
  +docs:
    node_color: "#cd7f32"

models:
  jaffle_shop:
    example:
      +materialized: table
    staging:
      +materialized: view
      +docs:
        node_color: "#c0c0c0"
    marts:
      +materialized: table
      +docs:
        node_color: "#ffd700"



flags:
  use_materialization_v2: true
